# 配置服务端 到GitHub中 通过 Git 获取配置
server:
  port: 4396
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: easygou-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xsyzb/easygou--.git #服务端配置GitHub上的路径
          username: xsyzb
          password: punchlove@123